server:
  port: 9002
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hujunr1991/spring-cloud-examples.git     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: hujunr1991                                          # git仓库的账号
          password: 888999Hw/                                        # git仓库的密码
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
